spin_manifest_version = 2

[application]
name = "nystrands"
version = "0.1.0"
authors = ["Timo Sulg <timgluz@gmail.com>"]
description = "Solver for NYTimes Strands"

[[trigger.http]]
route = "/..."
component = "nystrands"

[component.nystrands]
source = "main.wasm"
allowed_outbound_hosts = []
[component.nystrands.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/puzzles"
component = "puzzles"

[component.puzzles]
source = "puzzles/main.wasm"
allowed_outbound_hosts = []
[component.puzzles.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "puzzles"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/solve"
component = "solver"

[component.solver]
source = "solver/main.wasm"
allowed_outbound_hosts = []
[component.solver.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "solver"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/search"
component = "search"

[component.search]
source = "search/main.wasm"
allowed_outbound_hosts = []
[component.search.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "search"
watch = ["**/*.go", "go.mod"]
